from __future__ import annotations

from typing import Any

from django.conf import settings


class AIService:
    """Simple provider wrapper. Replace the mock branch with real LLM integration."""

    def generate_questions(self, *, subject: str, topic: str | None, count: int, difficulty: str) -> list[dict[str, Any]]:
        if settings.AI_PROVIDER != "mock" and not settings.OPENAI_API_KEY:
            raise ValueError("OPENAI_API_KEY is required for non-mock AI provider")

        topic_text = topic or "General"
        generated = []
        for index in range(count):
            generated.append(
                {
                    "question_text": f"[{difficulty}] {subject} question {index + 1} ({topic_text})",
                    "option_a": "Option A",
                    "option_b": "Option B",
                    "option_c": "Option C",
                    "option_d": "Option D",
                    "correct_answer": "A",
                    "simple_explanation": "Simple explanation generated by AI.",
                    "detailed_explanation": "Detailed explanation generated by AI.",
                    "deep_explanation": "Deep explanation generated by AI.",
                }
            )
        return generated
