# Generated by Django 5.1.7 on 2026-03-05 12:29

import django.db.models.deletion
from django.db import migrations, models


def copy_user_departments(apps, schema_editor):
    Department = apps.get_model("questions", "Department")
    User = apps.get_model("users", "User")

    for user in User.objects.all().iterator():
        name = (user.department or "").strip()
        if not name:
            continue
        department, _ = Department.objects.get_or_create(name=name)
        user.department_fk_id = department.id
        user.save(update_fields=["department_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0003_department_alter_subject_unique_together_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="questions.department",
            ),
        ),
        migrations.RunPython(copy_user_departments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="department_fk",
            new_name="department",
        ),
    ]
