# Generated by ChatGPT on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_department"),
        ("questions", "0003_department_alter_subject_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_sub",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="PendingRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=150)),
                ("password_hash", models.CharField(max_length=128)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("grade12", "Grade 12 Entrance Exam"),
                            ("exit", "University Exit Exam"),
                        ],
                        default="grade12",
                        max_length=20,
                    ),
                ),
                ("verification_code", models.CharField(max_length=6)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_registrations",
                        to="questions.department",
                    ),
                ),
            ],
        ),
    ]
