# Generated by Django 5.1.7 on 2026-03-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=120)),
                (
                    "question_type",
                    models.CharField(default="multiple_choice", max_length=50),
                ),
                ("question_text", models.TextField()),
                ("option_a", models.CharField(max_length=300)),
                ("option_b", models.CharField(max_length=300)),
                ("option_c", models.CharField(max_length=300)),
                ("option_d", models.CharField(max_length=300)),
                ("correct_answer", models.CharField(max_length=1)),
                ("simple_explanation", models.TextField(blank=True)),
                ("detailed_explanation", models.TextField(blank=True)),
                ("deep_explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("past_exam", "Past Exam"),
                            ("model_exam", "Model Exam"),
                            ("class_exam", "Class Exam"),
                            ("ai_generated", "AI Generated"),
                        ],
                        default="past_exam",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("grade12", "Grade 12"), ("exit", "University Exit")],
                        max_length=20,
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100)),
                ("course", models.CharField(blank=True, max_length=120)),
                ("questions_count", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
