# Generated by Django 5.1.7 on 2026-03-05 12:29

import django.db.models.deletion
from django.db import migrations, models


def copy_subject_departments(apps, schema_editor):
    Department = apps.get_model("questions", "Department")
    Subject = apps.get_model("questions", "Subject")

    for subject in Subject.objects.all().iterator():
        name = (subject.department or "").strip()
        if not name:
            continue
        department, _ = Department.objects.get_or_create(name=name)
        subject.department_fk_id = department.id
        subject.save(update_fields=["department_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subject",
            name="grade_level",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (9, "Grade 9"),
                    (10, "Grade 10"),
                    (11, "Grade 11"),
                    (12, "Grade 12"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to="questions.department",
            ),
        ),
        migrations.RunPython(copy_subject_departments, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="subject",
            name="department",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="department_fk",
            new_name="department",
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("name", "exam_type", "department", "grade_level"),
                name="unique_subject_per_track_scope",
            ),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="course",
        ),
    ]
