# Generated by Django 5.1.7 on 2026-03-21 11:50

import apps.questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_rich_explanation_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="deep_explanation_rich",
            field=models.JSONField(
                blank=True, default=apps.questions.models.default_deep_explanation_rich
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="detailed_explanation_rich",
            field=models.JSONField(
                blank=True,
                default=apps.questions.models.default_detailed_explanation_rich,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="simple_explanation_rich",
            field=models.JSONField(
                blank=True,
                default=apps.questions.models.default_simple_explanation_rich,
            ),
        ),
    ]
