# Generated by Django 5.1.7 on 2026-03-21 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0002_initial"),
        ("questions", "0007_alter_question_deep_explanation_rich_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[("grade12", "Grade 12"), ("exit", "University Exit")],
                        max_length=20,
                    ),
                ),
                (
                    "grade12_stream",
                    models.CharField(
                        blank=True,
                        choices=[("natural", "Natural"), ("social", "Social")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (9, "Grade 9"),
                            (10, "Grade 10"),
                            (11, "Grade 11"),
                            (12, "Grade 12"),
                        ],
                        null=True,
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=10)),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("passing_score", models.PositiveSmallIntegerField(default=50)),
                ("instructions", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exam_blueprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exam_blueprints",
                        to="questions.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExamBlueprintSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(blank=True, max_length=120)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("past_exam", "Past Exam"),
                            ("model_exam", "Model Exam"),
                            ("class_exam", "Class Exam"),
                            ("ai_generated", "AI Generated"),
                        ],
                        default="any",
                        max_length=20,
                    ),
                ),
                ("question_count", models.PositiveIntegerField(default=3)),
                ("sort_order", models.PositiveIntegerField(default=1)),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="exams.examblueprint",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprint_sections",
                        to="questions.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
