# Generated by Django 5.1.7 on 2026-03-21 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_examblueprint_examblueprintsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="examblueprint",
            name="adaptive_difficulty",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="max_retake_attempts",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="negative_mark_per_wrong",
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="negative_marking_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="retake_cooldown_minutes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="section_locking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="shuffle_options",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="shuffle_questions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="timed_sections",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examblueprintsection",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examresult",
            name="blueprint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="results",
                to="exams.examblueprint",
            ),
        ),
        migrations.AddField(
            model_name="examresult",
            name="weighted_score",
            field=models.FloatField(default=0),
        ),
    ]
