# Generated by Django 5.1.7 on 2026-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0004_examblueprint_adaptive_difficulty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examblueprint",
            name="anti_cheat_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="auto_submit_on_anti_cheat",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="fail_fast_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="fail_fast_min_failed_sections",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="examblueprint",
            name="max_blur_warnings",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name="examblueprintsection",
            name="pass_threshold_percentage",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
